id: PF7A34B4B
initial_creation_type: input
source_metadata:
  title: Vasubandhu
  language: en
  description: 'Texts by and about the great Indian paṇḍita Vasubandhu (dbyig gnyen),
    author of the Treasury of Abhidharma and other treatises:'
  volume:
    ee25af6ed7124609b1c527e7759a41cd:
      title: 'Light on the Path of Liberation: The Life of the Second Buddha Vasubandhu'
      parent: Biography
    db298875c841417abe75e9027ea0eb07:
      title: In Praise of the Three Jewels
      parent: Praise
created_at: '2022-03-01T02:26:39.734287'
last_modified_at: '2022-03-01T02:26:39.734295'
